//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiFormulario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudadano
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string ocupacion { get; set; }
        public string nacionalidad { get; set; }
        public string cedula { get; set; }
        public string piel { get; set; }
    }
}
